In [1]:
import numpy as np

l=[1,2,3,4,5]
ar=np.array(l)

print(ar)
print(type(ar))
print(ar.shape)
print(ar.dtype)
print(ar.ndim)
print(ar.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int32
1
5


In [2]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=[11,12,13,14,15]
mda=np.array([l1,l2,l3])

print(mda,'\n')
print(mda.shape,'\n')

print(mda.reshape(5,3),'\n')

print(mda[1:,3:])




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

(3, 5) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]] 

[[ 9 10]
 [14 15]]


In [3]:
arr=np.array([1,2,3,4,5])
print(arr[3])

arr[2:4] = 10
print(arr)

4
[ 1  2 10 10  5]


In [4]:
arr=np.arange(0,10)
v=np.arange(0,10,2)

print(arr)
print(v,'\n')

#broadcasting
arr[3:]=100
print(arr)

ar1=arr
ar1[3:]=500
print(ar1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8] 

[  0   1   2 100 100 100 100 100 100 100]
[  0   1   2 500 500 500 500 500 500 500]
[  0   1   2 500 500 500 500 500 500 500]


In [5]:
arr=np.array([1,2,3,4,5])
var=3
print(arr>3)
print(arr[arr>3],'\n')

print(arr<=2,'\n')

print(arr*var)


[False False False  True  True]
[4 5] 

[ True  True False False False] 

[ 3  6  9 12 15]


In [6]:
print(np.arange(0,10).reshape(5,2)) # 5 rows, 2 columns

print()

print(np.arange(0,10).reshape(2,5)) # 2 rows,


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [42]:
print(np.random.rand(3,3))# Random values in (0.0, 1.0)
print()

print(np.random.randint(2,10,6))# Random integers from low (inclusive) to high (exclusive)
print()

print(np.random.randint(1,10,(3,3)))# Random integers from low (inclusive) to high (exclusive)

[[0.65591733 0.54414302 0.33626551]
 [0.49398825 0.9251087  0.67105539]
 [0.22444689 0.73315378 0.35451229]]

[4 8 9 9 5 9]

[[8 1 7]
 [3 3 2]
 [6 9 2]]
