In [18]:
import numpy as np
import pandas as pd 

In [19]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['column1','column2','column3','column4'])
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [20]:
#Accessing elements
print(df["column1"]["row1"],'\n')

print(df["column1"],'\n')

print(df["column1"].value_counts(),'\n')

df["column1"].unique()


0 

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int32 

column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64 



array([ 0,  4,  8, 12, 16])

In [22]:

print(df.loc['row1'],'\n')

print(type(df.loc['row1']),'\n')

print(df.loc['row2':'row4','column2':'column4'],'\n')


print(df.loc['row1']['column1'],'\n')
print(df.loc['row1','column1'],'\n')

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int32 

<class 'pandas.core.series.Series'> 

      column2  column3  column4
row2        5        6        7
row3        9       10       11
row4       13       14       15 

0 

0 



In [28]:
print(df.iloc[:,:])
print(type(df.iloc[:,:]),'\n')

print(df.iloc[:3,0])
print(type(df.iloc[:3,0]),'\n')

print(df.iloc[1:3,2:4])


      column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19
<class 'pandas.core.frame.DataFrame'> 

row1    0
row2    4
row3    8
Name: column1, dtype: int32
<class 'pandas.core.series.Series'> 

      column3  column4
row2        6        7
row3       10       11


In [30]:
#converting the DataFrame to a NumPy array
print(df.iloc[:,1:],'\n')

print(df.iloc[:,1:].values,'\n')

df.iloc[:,1:].values.shape

      column2  column3  column4
row1        1        2        3
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]] 



(5, 3)

In [ ]:
df.isnull()

column1  column2  column3  column4
row1    False    False    False    False
row2    False    False    False    False
row3    False    False    False    False
row4    False    False    False    False
row5    False    False    False    False

READING CSV WITH PANDAS

In [31]:
df=pd.read_csv("D:\Study\Learning-Fundamentals\Datasets\merc.csv")

In [33]:
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0        SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1    S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2   SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3    G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4    G Class  2016  73948    Automatic     4000   Petrol  325  30.1   

   engineSize  
0         1.8  
1         2.1  
2         5.5  
3         4.0  
4         4.0