In [3]:
import numpy as np
import pandas as pd 

In [161]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['column1','column2','column3','column4'])
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [196]:
#Accessing column
print(df["column1"],'\n')

print(df["column1"].value_counts(),'\n')

df["column1"].unique()


row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int32 

column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64 



array([ 0,  4,  8, 12, 16])

In [201]:
# Accessing a specific row by index
print(df.loc['row1'],'\n')

print(type(df.loc['row1']))



column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int32 

<class 'pandas.core.series.Series'>


In [124]:
print(df.iloc[:,:],'\n')

print(df.iloc[:3,0])
print(type(df.iloc[:3,0]))

      column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19 

row1    0
row2    4
row3    8
Name: column1, dtype: int32
<class 'pandas.core.series.Series'>


In [ ]:
#converting the DataFrame to a NumPy array
print(df.iloc[:,1:],'\n')

print(df.iloc[:,1:].values,'\n')

df.iloc[:,1:].values.shape

      column2  column3  column4
row1        1        2        3
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]] 



(5, 3)

In [154]:
df.isnull()

column1  column2  column3  column4
row1    False    False    False    False
row2    False    False    False    False
row3    False    False    False    False
row4    False    False    False    False
row5    False    False    False    False