In [1]:
import numpy as np
import pandas as pd 

In [2]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['column1','column2','column3','column4'])
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [3]:
#Accessing elements
print(df["column1"]["row1"],'\n')

print(df["column1"],'\n')

print(df["column1"].value_counts(),'\n')

df["column1"].unique()


0 

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int32 

column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64 



array([ 0,  4,  8, 12, 16])

In [4]:

print(df.loc['row1'],'\n')

print(type(df.loc['row1']),'\n')

print(df.loc['row2':'row4','column2':'column4'],'\n')


print(df.loc['row1']['column1'],'\n')
print(df.loc['row1','column1'],'\n')

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int32 

<class 'pandas.core.series.Series'> 

      column2  column3  column4
row2        5        6        7
row3        9       10       11
row4       13       14       15 

0 

0 



In [5]:
print(df.iloc[:,:])
print(type(df.iloc[:,:]),'\n')

print(df.iloc[:3,0])
print(type(df.iloc[:3,0]),'\n')

print(df.iloc[1:3,2:4])


      column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19
<class 'pandas.core.frame.DataFrame'> 

row1    0
row2    4
row3    8
Name: column1, dtype: int32
<class 'pandas.core.series.Series'> 

      column3  column4
row2        6        7
row3       10       11


In [6]:
#converting the DataFrame to a NumPy array
print(df.iloc[:,1:],'\n')

print(df.iloc[:,1:].values,'\n')

df.iloc[:,1:].values.shape

      column2  column3  column4
row1        1        2        3
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]] 



(5, 3)

In [7]:
df.isnull()

column1  column2  column3  column4
row1    False    False    False    False
row2    False    False    False    False
row3    False    False    False    False
row4    False    False    False    False
row5    False    False    False    False

READING CSV WITH PANDAS

In [8]:
df=pd.read_csv("D:\Study\Learning-Fundamentals\Datasets\merc.csv")

In [9]:
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0        SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1    S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2   SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3    G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4    G Class  2016  73948    Automatic     4000   Petrol  325  30.1   

   engineSize  
0         1.8  
1         2.1  
2         5.5  
3         4.0  
4         4.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13119 entries, 0 to 13118
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         13119 non-null  object 
 1   year          13119 non-null  int64  
 2   price         13119 non-null  int64  
 3   transmission  13119 non-null  object 
 4   mileage       13119 non-null  int64  
 5   fuelType      13119 non-null  object 
 6   tax           13119 non-null  int64  
 7   mpg           13119 non-null  float64
 8   engineSize    13119 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 922.6+ KB


In [11]:
df.describe()

year          price        mileage           tax           mpg  \
count  13119.000000   13119.000000   13119.000000  13119.000000  13119.000000   
mean    2017.296288   24698.596920   21949.559037    129.972178     55.155843   
std        2.224709   11842.675542   21176.512267     65.260286     15.220082   
min     1970.000000     650.000000       1.000000      0.000000      1.100000   
25%     2016.000000   17450.000000    6097.500000    125.000000     45.600000   
50%     2018.000000   22480.000000   15189.000000    145.000000     56.500000   
75%     2019.000000   28980.000000   31779.500000    145.000000     64.200000   
max     2020.000000  159999.000000  259000.000000    580.000000    217.300000   

         engineSize  
count  13119.000000  
mean       2.071530  
std        0.572426  
min        0.000000  
25%        1.800000  
50%        2.000000  
75%        2.100000  
max        6.200000

In [12]:
df["transmission"].value_counts()

transmission
Semi-Auto    6848
Automatic    4825
Manual       1444
Other           2
Name: count, dtype: int64

In [13]:
print(df["tax"]>100)

df[df["tax"]>100]



0         True
1        False
2         True
3         True
4         True
         ...  
13114     True
13115     True
13116     True
13117     True
13118     True
Name: tax, Length: 13119, dtype: bool


model  year   price transmission  mileage fuelType  tax   mpg  \
0             SLK  2005    5200    Automatic    63000   Petrol  325  32.1   
2        SL CLASS  2016   49948    Automatic     6200   Petrol  555  28.0   
3         G Class  2016   61948    Automatic    16000   Petrol  325  30.4   
4         G Class  2016   73948    Automatic     4000   Petrol  325  30.1   
5        SL CLASS  2011  149948    Automatic     3000   Petrol  570  21.4   
...           ...   ...     ...          ...      ...      ...  ...   ...   
13114     C Class  2020   35999    Automatic      500   Diesel  145  55.4   
13115     B Class  2020   24699    Automatic     2500   Diesel  145  55.4   
13116   GLC Class  2019   30999    Automatic    11612   Diesel  145  41.5   
13117   CLS Class  2019   37990    Automatic     2426   Diesel  145  45.6   
13118     S Class  2019   54999    Automatic     2075   Diesel  145  52.3   

       engineSize  
0             1.8  
2             5.5  
3             4.0  
4             4.0  
5             6.2  
...           ...  
13114         2.0  
13115         2.0  
13116         2.1  
13117         2.0  
13118         2.9  

[10705 rows x 9 columns]